version: '3'

services:
  dotnet:
    build: .
    networks:
      - default
      - backend
    depends_on:
      - postgis

  postgis:
    image: mdillon/postgis:9.4-alpine
    networks:
      - backend
    environment:
      POSTGRES_USER: n50kartdata
      POSTGRES_PASSWORD: n50kartdata
      POSTGRES_DB: n50kartdata
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb.d/restore.sh:/docker-entrypoint-initdb.d/z10_restore.sh
      - ./initdb.d/rename.sql:/docker-entrypoint-initdb.d/z20_rename.sql
      - ./n50kartdata.tmp/Basisdata_0000_Norge_25833_N50Kartdata_PostGIS.backup:/tmp/N50Kartdata.backup
    restart: always

networks:
  default:
    external: true
    name: dataplattform_etl
  backend:

volumes:
  db_data:
